#!/usr/bin/env python3
"""Generate paper/numbers.tex from p_a_numbers.json.

Defines a set of LaTeX macros used in main.tex. Re-running this script
after new eval JSONs land is the only thing needed to refresh the paper.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NUMS = ROOT / "paper" / "figures" / "p_a_numbers.json"
OUT = ROOT / "paper" / "numbers.tex"
EVAL_DIR = ROOT / "results" / "eval_v25_seed_pack_evpos"


def _f(x, fmt="%+.3f"):
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "n/a"
    return fmt % x


def _v27_summary_from_seeds(label_prefix: str, seed_files: list[str]) -> tuple[str, int, list[float]]:
    """Read each seed's v27a/v27c JSON, return mean string and seed-list."""
    vals = []
    for fn in seed_files:
        p = EVAL_DIR / fn
        if not p.exists():
            continue
        d = json.loads(p.read_text())
        v = next(iter(d.values()))
        vals.append(v["pa_cb_dnm"])
    if not vals:
        return "(pending)", 0, []
    import statistics as st
    if len(vals) == 1:
        s = f"${vals[0]:+.3f}$ (n${{=}}1$)"
    else:
        m = st.mean(vals)
        sd = st.stdev(vals)
        s = f"${m:+.3f} \\pm {sd:.3f}$ (n${{=}}{len(vals)}$)"
    return s, len(vals), vals


def main() -> None:
    nums = json.loads(NUMS.read_text())
    lines: list[str] = []
    L = lines.append

    L("% Auto-generated by paper/scripts/render_numbers_tex.py")
    L("% Source: paper/figures/p_a_numbers.json + raw JSONs in results/")
    L("% DO NOT EDIT BY HAND -- re-run the script.")
    L("")

    # === 1.7B v28 expanded seed pack (the main update v28c/v28d will trigger)
    m17 = nums.get("memres_1p7b_v28", {})
    n17 = m17.get("n_seeds", 0)
    if n17:
        d17_mean = m17["dnm_seed_mean"]
        d17_ci   = m17["per_chain_pooled_bootstrap_95ci"]
        d17_dsh  = m17["dsh_seed_mean"]
        d17_evl  = m17["evlift_seed_mean"]
        d17_pos_pooled = m17["per_chain_pooled_pos_count"]
        d17_total_pooled = m17["per_chain_pooled_total"]
        d17_per_seed_pos = round(d17_pos_pooled / max(1, n17))
        # All math-mode macros emit BARE math content (no surrounding $...$);
        # callers wrap with $...$ as needed.
        L(f"\\newcommand{{\\NSEEDSseventeen}}{{{n17}}}")
        if n17 >= 2:
            L(f"\\newcommand{{\\Dseventeenmean}}{{{d17_mean['mean']:+.3f} \\pm {d17_mean['std']:.3f}}}")
        else:
            L(f"\\newcommand{{\\Dseventeenmean}}{{{d17_mean['mean']:+.3f}}}")
        L(f"\\newcommand{{\\Dseventeenci}}{{[{d17_ci[0]:+.3f},\\,{d17_ci[1]:+.3f}]}}")
        L(f"\\newcommand{{\\Dseventeendsh}}{{{d17_dsh['mean']:+.3f}}}")
        L(f"\\newcommand{{\\Dseventeenevl}}{{{d17_evl['mean']:+.3f}}}")
        L(f"\\newcommand{{\\Dseventeenpos}}{{{d17_per_seed_pos}}}")
        # Per-seed rows for the appendix raw table
        rows = []
        for fn in m17["files"]:
            p = EVAL_DIR / fn
            if not p.exists(): continue
            d = json.loads(p.read_text())
            v = next(iter(d.values()))
            # extract seed number from filename
            seed = fn.split("seed")[1].split("_")[0] if "seed" in fn else "1"
            cell = "v28a" if "v28a" in fn else "v28b" if "v28b" in fn else "v28c" if "v28c" in fn else "v28d"
            rows.append(f"1.7B {cell} (no F3) & {seed} & ${v['pa_cb_dnm']:+.3f}$ & ${v['pa_cb_dsh']:+.3f}$ & ${v.get('pa_cb_evidence_lift', float('nan')):+.3f}$ \\\\")
        # Drop the first two rows (those are already explicit in main.tex);
        # only emit any extra rows beyond seeds 1, 2.
        extra = rows[2:] if len(rows) > 2 else []
        if extra:
            sep = " \\hline "
            joined = sep.join(extra)
            L(f"\\newcommand{{\\Vtwentyeightcdrows}}{{ {joined} \\hline }}")
            extra_seeds = [int(fn.split('seed')[1].split('_')[0]) for fn in m17["files"][2:]]
            seeds_str = " and ".join(str(s) for s in extra_seeds)
            L(f"\\newcommand{{\\Vtwentyeightcdremark}}{{seeds {seeds_str} added}}")
        else:
            L("\\newcommand{\\Vtwentyeightcdrows}{}")
            L("\\newcommand{\\Vtwentyeightcdremark}{seeds 3 and 4 in flight}")
    else:
        L("\\newcommand{\\NSEEDSseventeen}{(pending)}")
        L("\\newcommand{\\Dseventeenmean}{$+0.000$}")
        L("\\newcommand{\\Dseventeenci}{$[\\,]$}")
        L("\\newcommand{\\Dseventeendsh}{$0.000$}")
        L("\\newcommand{\\Dseventeenevl}{$0.000$}")
        L("\\newcommand{\\Dseventeenpos}{0}")
        L("\\newcommand{\\Vtwentyeightcdrows}{}")
        L("\\newcommand{\\Vtwentyeightcdremark}{seeds in flight}")

    # === Ablation summaries (v27a / v27c)
    v27a_files = [
        "v27a_no_depth_final_lme_val_evpos.json",
        "v27a_v24a_no_depth_seed2_0p6b_frozen_local_lme_val_evpos.json",
        "v27a_v24a_no_depth_seed3_0p6b_frozen_local_lme_val_evpos.json",
        "v27a_v24a_no_depth_seed4_0p6b_frozen_local_lme_val_evpos.json",
    ]
    v27c_files = [
        "v27c_no_floor_final_lme_val_evpos.json",
        "v27c_v24a_no_floor_seed2_0p6b_frozen_local_lme_val_evpos.json",
        "v27c_v24a_no_floor_seed3_0p6b_frozen_local_lme_val_evpos.json",
        "v27c_v24a_no_floor_seed4_0p6b_frozen_local_lme_val_evpos.json",
    ]
    v27a_sum, n_v27a, _ = _v27_summary_from_seeds("v27a", v27a_files)
    v27c_sum, n_v27c, _ = _v27_summary_from_seeds("v27c", v27c_files)
    L(f"\\newcommand{{\\VtwentysevenA}}{{{v27a_sum}}}  % no-depth ablation")
    L(f"\\newcommand{{\\Vtwentysevenc}}{{{v27c_sum}}}  % no-floor ablation")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"saved -> {OUT}")
    print(f"  v28 1.7B n_seeds = {n17}")
    print(f"  v27a no-depth: {v27a_sum}  (n={n_v27a})")
    print(f"  v27c no-floor: {v27c_sum}  (n={n_v27c})")


if __name__ == "__main__":
    main()
